workflows:
  android-debug-build:
    name: Stayer Debug APK
    max_build_duration: 15
    instance_type: mac_mini_m1
    environment:
      android_sdk: 34
      java: 17
    scripts:
      - name: Set up local.properties
        script: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: chmod gradlew
        script: chmod +x gradlew
      - name: Build Android Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - alexeyovch26@gmail.com
