workflows:
  android-debug-build:
    name: Stayer Debug APK
    max_build_duration: 15
    instance_type: mac_mini_m1
    environment:
      java: 17
    scripts:
      - name: chmod gradlew
        script: chmod +x gradlew
      - name: Build Android Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
    publishing:
      email:
        recipients:
          - YOUR_EMAIL_HERE
