import Foundation

enum Strings {
    static let appName = NSLocalizedString("app_name", comment: "")
    static let infoTitle = NSLocalizedString("info_title", comment: "")
    static let infoBody = NSLocalizedString("info_body", comment: "")
    static let infoEmail = NSLocalizedString("info_email", comment: "")
    static let infoCard = NSLocalizedString("info_card", comment: "")
    static let infoOpenSetup = NSLocalizedString("info_open_setup", comment: "")

    static let mainHistory = NSLocalizedString("main_history", comment: "")
    static let mainInfo = NSLocalizedString("main_info", comment: "")
    static let mainStart = NSLocalizedString("main_start", comment: "")
    static let mainPause = NSLocalizedString("main_pause", comment: "")
    static let mainHoldHint = NSLocalizedString("main_hold_hint", comment: "")
    static let mainTime = NSLocalizedString("main_time", comment: "")
    static let mainDistance = NSLocalizedString("main_distance", comment: "")
    static let mainPace = NSLocalizedString("main_pace", comment: "")
    static let mainGoal = NSLocalizedString("main_goal", comment: "")
    static let mainSetGoal = NSLocalizedString("main_set_goal", comment: "")

    static let goalTitle = NSLocalizedString("goal_title", comment: "")
    static let goalDistanceLabel = NSLocalizedString("goal_distance_label", comment: "")
    static let goalDistancePlaceholder = NSLocalizedString("goal_distance_placeholder", comment: "")
    static let goalTimeLabel = NSLocalizedString("goal_time_label", comment: "")
    static let goalTimePlaceholder = NSLocalizedString("goal_time_placeholder", comment: "")
    static let goalSaveDistance = NSLocalizedString("goal_save_distance", comment: "")
    static let goalSaveTime = NSLocalizedString("goal_save_time", comment: "")
    static let goalSavedDistance = NSLocalizedString("goal_saved_distance", comment: "")
    static let goalSavedTime = NSLocalizedString("goal_saved_time", comment: "")

    static let historyTitle = NSLocalizedString("history_title", comment: "")
    static let historyPaceLabel = NSLocalizedString("history_pace_label", comment: "")

    static let setupTitle = NSLocalizedString("setup_title", comment: "")
    static let setupLocationAlways = NSLocalizedString("setup_location_always", comment: "")
    static let setupNotifications = NSLocalizedString("setup_notifications", comment: "")
    static let setupMotion = NSLocalizedString("setup_motion", comment: "")
    static let setupRequest = NSLocalizedString("setup_request", comment: "")
    static let setupOpenSettings = NSLocalizedString("setup_open_settings", comment: "")
    static let setupDone = NSLocalizedString("setup_done", comment: "")
    static let setupStatusGranted = NSLocalizedString("setup_status_granted", comment: "")
    static let setupStatusDenied = NSLocalizedString("setup_status_denied", comment: "")
    static let setupStatusRestricted = NSLocalizedString("setup_status_restricted", comment: "")
    static let setupStatusNotRequested = NSLocalizedString("setup_status_not_requested", comment: "")
    static let setupStatusWhenInUse = NSLocalizedString("setup_status_when_in_use", comment: "")

    static let alertLocationTitle = NSLocalizedString("alert_location_title", comment: "")
    static let alertLocationMessage = NSLocalizedString("alert_location_message", comment: "")
    static let alertOk = NSLocalizedString("alert_ok", comment: "")
    static let alertLocationUpgradeTitle = NSLocalizedString("alert_location_upgrade_title", comment: "")
    static let alertLocationUpgradeMessage = NSLocalizedString("alert_location_upgrade_message", comment: "")
    static let alertAllow = NSLocalizedString("alert_allow", comment: "")
}
